# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  script:
    description: 'Script to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - '${{ inputs.script }}'
