# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  script:
    description: 'Script to run'
    required: true
  firecrest_client_id:
    description: "FirecREST client ID (aka Consumer Key)"
    required: true
  firecrest_client_secret:
    description: "FirecREST client secret (aka Consumer Secret)"
    required: true
  firecrest_url:
    description: "FirecREST URL"
    required: true
    default: "https://api.cscs.ch/hpc/firecrest"
  firecrest_system:
    description: "FirecREST machine"
    required: true
    default: "daint"
  firecrest_token_url:
    description: "FirecREST token URL"
    required: true
    default: "https://auth.cscs.ch/auth/realms/firecrest-clients/protocol/openid-connect/token"
  stage_to_compute_node:
    description: "Stage workspace and github env/output files to compute node"
    required: true
    default: "true"
  stage_from_compute_node:
    description: "Stage workspace and github env/output files from compute node"
    required: true
    default: "true"
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - '${{ inputs.script }}'
