# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  script:
    description: 'Script to run'
    required: true
  firecrest-client-id:
    description: "FirecREST client ID (aka Consumer Key)"
    required: true
  firecrest-client-secret:
    description: "FirecREST client secret (aka Consumer Secret)"
    required: true
  firecrest-url:
    description: "FirecREST URL"
    required: true
    default: "https://api.cscs.ch/hpc/firecrest"
  firecrest-system:
    description: "FirecREST machine"
    required: true
    default: "daint"
  firecrest-token-url:
    description: "FirecREST token URL"
    required: true
    default: "https://auth.cscs.ch/auth/realms/firecrest-clients/protocol/openid-connect/token"
  stage-to-compute-node:
    description: "Stage workspace and github env/output files to compute node"
    required: true
    default: "true"
  stage-from-compute-node:
    description: "Stage workspace and github env/output files from compute node"
    required: true
    default: "true"
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - '${{ inputs.script }}'
